apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-lab-secret
  namespace: spring-boot-lab
type: Opaque
stringData:
  DB_PASSWORD: replace-me
  SPRING_FLYWAY_USER: replace-me
  SPRING_FLYWAY_PASSWORD: replace-me
  JWT_SECRET: replace-with-a-strong-secret
