apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-lab-config
  namespace: spring-boot-lab
data:
  SPRING_PROFILES_ACTIVE: local

  DB_URL: jdbc:postgresql://postgres:5432/spring_boot_lab
  DB_USERNAME: ravan

  REDIS_SENTINEL_MASTER: mymaster
  REDIS_SENTINEL_NODES: "redis-sentinel-0.redis-sentinel-headless.spring-boot-lab.svc.cluster.local:26379,redis-sentinel-1.redis-sentinel-headless.spring-boot-lab.svc.cluster.local:26379,redis-sentinel-2.redis-sentinel-headless.spring-boot-lab.svc.cluster.local:26379"
  REDIS_CONNECT_TIMEOUT: "2s"
  REDIS_COMMAND_TIMEOUT: "2s"

  KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  OTEL_ENABLED: "false"

  OUTBOX_RETRY_BASE_DELAY_SECONDS: "5"
  OUTBOX_RETRY_MAX_DELAY_SECONDS: "300"
  OUTBOX_RETRY_JITTER_FACTOR: "0.20"
