apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-lab
  namespace: spring-boot-lab
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: spring-boot-lab

  template:
    metadata:
      labels:
        app: spring-boot-lab

    spec:
      terminationGracePeriodSeconds: 40

      containers:
        - name: app
          image: spring_boot_lab-app:phase3
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - configMapRef:
                name: spring-boot-lab-config
            - secretRef:
                name: spring-boot-lab-secret

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 1Gi

          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-lab
  namespace: spring-boot-lab
spec:
  selector:
    app: spring-boot-lab
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
