apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: spring-boot-lab
type: Opaque
stringData:
  POSTGRES_DB: spring_boot_lab
  POSTGRES_USER: ravan
  POSTGRES_PASSWORD: replace-me
