name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: spring_boot_lab
          POSTGRES_USER: ravan
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U ravan -d spring_boot_lab"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build and test
        run: ./mvnw clean test
        env:
          DB_URL: jdbc:postgresql://localhost:5433/spring_boot_lab
          DB_USERNAME: ravan
          DB_PASSWORD: password
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
